title: Sangam Kumar
description: >
  
permalink: ':title/'
site-twitter:

author: Sangam Kumar
author-img: sangam.jpg
about-author: I am a web developer focusing on front-end development. Always hungry to keep learning.
social-twitter: meetsangamcse
social-facebook: cashewsangam
social-github: sangamcse
social-linkedin: sangamcse
social-email: ksangam68@gmail.com

subscribe_rss: /feed.xml

discus-identifier: meetsangamcse 

# Tracker
analytics: UA-118439543-1

# Build Settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
