title: Sangam Kumar
description: >
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
site-twitter:

author: Sangam Kumar
author-img: sangam.jpg
about-author: I am a web developer focusing on front-end development. Always hungry to keep learning.
social-twitter: meetsangamcse
social-facebook: cashewsangam
social-github: sangamcse
social-linkedin: sangamcse
social-email: ksangam68@gmail.com

discus-identifier: meetsangamcse 

# Tracker
analytics: UA-118439543-1

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
